import type { NetworkSnapshot } from "@/lib/network/network";

export function createSeedNetworkSnapshot(): NetworkSnapshot {
  return {
    connections: [
      {
        id: "c-1",
        fullName: "Maya Rodriguez",
        headline: "Senior Product Designer at Figma",
        location: "San Francisco, CA",
        mutualCount: 18,
        sharedSkills: ["Design Systems", "Prototyping", "Mentorship"],
      },
      {
        id: "c-2",
        fullName: "Jordan Lee",
        headline: "Staff Frontend Engineer at Stripe",
        location: "Seattle, WA",
        mutualCount: 12,
        sharedSkills: ["React", "TypeScript", "Accessibility"],
      },
      {
        id: "c-3",
        fullName: "Priya Nair",
        headline: "Engineering Manager at Atlassian",
        location: "Austin, TX",
        mutualCount: 9,
        sharedSkills: ["People Management", "Roadmapping", "Hiring"],
      },
      {
        id: "c-4",
        fullName: "Owen Carter",
        headline: "Principal Platform Engineer at Notion",
        location: "New York, NY",
        mutualCount: 11,
        sharedSkills: ["System Design", "API Architecture", "Go"],
      },
      {
        id: "c-5",
        fullName: "Avery Kim",
        headline: "Growth Product Manager at Webflow",
        location: "Los Angeles, CA",
        mutualCount: 7,
        sharedSkills: ["Experimentation", "Analytics", "Product Strategy"],
      },
      {
        id: "c-6",
        fullName: "Noah Brooks",
        headline: "Senior Backend Engineer at Supabase",
        location: "Denver, CO",
        mutualCount: 14,
        sharedSkills: ["Postgres", "FastAPI", "Reliability"],
      },
      {
        id: "c-7",
        fullName: "Emma Davis",
        headline: "UX Research Lead at Shopify",
        location: "Chicago, IL",
        mutualCount: 6,
        sharedSkills: ["User Interviews", "Insights", "Experiment Design"],
      },
      {
        id: "c-8",
        fullName: "Liam Patel",
        headline: "Senior Data Engineer at Datadog",
        location: "Boston, MA",
        mutualCount: 10,
        sharedSkills: ["Data Pipelines", "SQL", "Observability"],
      },
    ],
    incoming: [
      {
        id: "i-1",
        fullName: "Sofia Bennett",
        headline: "Frontend Developer at Vercel",
        location: "Brooklyn, NY",
        mutualCount: 5,
        sharedSkills: ["Next.js", "Tailwind", "Performance"],
      },
      {
        id: "i-2",
        fullName: "Marcus Chen",
        headline: "Product Analyst at Airbnb",
        location: "San Diego, CA",
        mutualCount: 4,
        sharedSkills: ["SQL", "Metrics", "Experimentation"],
      },
      {
        id: "i-3",
        fullName: "Elena Petrova",
        headline: "Technical Recruiter at Scale AI",
        location: "Miami, FL",
        mutualCount: 2,
        sharedSkills: ["Hiring", "Talent Strategy", "Partnerships"],
      },
      {
        id: "i-4",
        fullName: "Diego Alvarez",
        headline: "ML Engineer at Hugging Face",
        location: "Remote",
        mutualCount: 8,
        sharedSkills: ["Python", "MLOps", "NLP"],
      },
      {
        id: "i-5",
        fullName: "Hannah Nguyen",
        headline: "Developer Advocate at Cloudflare",
        location: "Portland, OR",
        mutualCount: 3,
        sharedSkills: ["Community", "API Docs", "Workshops"],
      },
      {
        id: "i-6",
        fullName: "Caleb Wright",
        headline: "Founding Engineer at Finch",
        location: "Austin, TX",
        mutualCount: 7,
        sharedSkills: ["Startups", "React", "Node.js"],
      },
    ],
    recommended: [
      {
        id: "r-1",
        fullName: "Grace Thompson",
        headline: "Design Engineer at Framer",
        location: "San Jose, CA",
        mutualCount: 16,
        sharedSkills: ["Interaction Design", "React", "Animations"],
      },
      {
        id: "r-2",
        fullName: "Miles O'Connor",
        headline: "Head of Product at Loom",
        location: "New York, NY",
        mutualCount: 9,
        sharedSkills: ["Product Leadership", "Go-to-Market", "Storytelling"],
      },
      {
        id: "r-3",
        fullName: "Rina Sato",
        headline: "Senior iOS Engineer at Duolingo",
        location: "Pittsburgh, PA",
        mutualCount: 5,
        sharedSkills: ["Swift", "Mobile UX", "A/B Testing"],
      },
      {
        id: "r-4",
        fullName: "Alex Morgan",
        headline: "Security Engineer at GitHub",
        location: "Remote",
        mutualCount: 11,
        sharedSkills: ["AppSec", "Threat Modeling", "DevSecOps"],
      },
      {
        id: "r-5",
        fullName: "Nadia Rahman",
        headline: "Data Scientist at OpenAI",
        location: "San Francisco, CA",
        mutualCount: 13,
        sharedSkills: ["Machine Learning", "Evaluation", "Python"],
      },
      {
        id: "r-6",
        fullName: "Ethan Miller",
        headline: "Solutions Architect at Snowflake",
        location: "Atlanta, GA",
        mutualCount: 4,
        sharedSkills: ["Cloud", "Architecture", "Enterprise"],
      },
      {
        id: "r-7",
        fullName: "Isabella Rossi",
        headline: "Creative Director at Canva",
        location: "Los Angeles, CA",
        mutualCount: 10,
        sharedSkills: ["Brand", "Visual Systems", "Creative Ops"],
      },
      {
        id: "r-8",
        fullName: "Tyler Johnson",
        headline: "Senior QA Automation Engineer at Linear",
        location: "Chicago, IL",
        mutualCount: 3,
        sharedSkills: ["Testing", "CI/CD", "Quality Engineering"],
      },
      {
        id: "r-9",
        fullName: "Lila Harper",
        headline: "Community Lead at Retool",
        location: "Denver, CO",
        mutualCount: 6,
        sharedSkills: ["Community", "Developer Relations", "Events"],
      },
      {
        id: "r-10",
        fullName: "Arjun Menon",
        headline: "Platform PM at Slack",
        location: "Seattle, WA",
        mutualCount: 8,
        sharedSkills: ["APIs", "Product Strategy", "Partnerships"],
      },
      {
        id: "r-11",
        fullName: "Chloe Park",
        headline: "Senior Product Marketing Manager at Notion",
        location: "Boston, MA",
        mutualCount: 5,
        sharedSkills: ["Messaging", "Launches", "Positioning"],
      },
      {
        id: "r-12",
        fullName: "Victor Silva",
        headline: "Cloud Infrastructure Engineer at DigitalOcean",
        location: "Miami, FL",
        mutualCount: 7,
        sharedSkills: ["Kubernetes", "Terraform", "SRE"],
      },
    ],
    outgoing: [],
  };
}
